name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Enable Corepack
      run: corepack enable
    - name: Prepare Yarn
      run: corepack prepare yarn@4.5.0 --activate
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Deploy
      run: yarn deploy